name: Dynamic Shell
description: Dynamically resolve and use custom Shell.
author: Takashi Kato
inputs:
  shell:
    description: Custom shell command, e.g. `bash`
    required: true
  run:
    description: Shell command string
    required: true
outputs:
  outputs:
    description: Shell execution output.
    value: ${{ steps.exec.outputs.outputs }}
runs:
  using: composite
  steps:
    - name: Indent
      id: indent
      shell: bash
      run: |
        input=$(echo $DYNAMIC_SHELL_ENV_INPUT | cut -c 2- | rev | cut -c 2- | rev)
        lines=()
        while IFS='' read -r value; do
          lines+=("$value")
        done <<-EOF
         $(printf "$input")
        EOF

        indent=""
        for j in {1..8}; do
          indent="$indent "
        done
        output=""
        for i in "${!lines[@]}"; do
          line="${lines[i]}"
          if [ "$output" == "" ]; then
            output="$indent${line//\"/\\\"}"
          else
            # adding one extra here, no idea why this happens
            # maybe the $GITHUB_OUTPUT thing?
            output="$output\n $indent${line//\"/\\\"}"
          fi
        done

        echo "lines=$output">> $GITHUB_OUTPUT
      env:
        DYNAMIC_SHELL_ENV_INPUT: ${{ toJSON(inputs.run) }}
    - name: Setup
      shell: bash
      run: |
        mkdir -p ./.tmp-dynamic-shell &&
        cat <<'DYNAMIC_SHELL_EOF' > ./.tmp-dynamic-shell/action.yml &&
        outputs:
          outputs:
            value: ${{ '$' }}{{ toJSON(steps.exec.outputs) }}
        runs:
          using: composite
          steps:
            - run: rm -rf ./.tmp-dynamic-shell
              shell: sh
            - name: Exec
              id: exec
              shell: ${{ inputs.shell }}
              run: |
        DYNAMIC_SHELL_EOF
        printf "$DYNAMIC_SHELL_ENV_INPUT\n" >> ./.tmp-dynamic-shell/action.yml
      env:
        DYNAMIC_SHELL_ENV_INPUT: ${{ steps.indent.outputs.lines }}
    - name: Exec
      id: exec
      uses: ./.tmp-dynamic-shell
    - name: Debug
      shell: bash
      run: echo "${{ steps.exec.outputs.outputs }}"
    - name: Cleanup
      if: always() && steps.exec.outcome != 'success'
      shell: bash
      run: rm -rf ./.tmp-dynamic-shell
